"""Esquema inicial: usuarios, examenes, calificaciones, rankings, reportes

Revision ID: bca1ffe1c0e4
Revises: 
Create Date: 2026-07-13 11:48:59.045888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca1ffe1c0e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('ADMINISTRADOR', 'DOCENTE', 'ESTUDIANTE', name='rolenum'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=True)

    op.create_table('credenciales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_sesion', sa.String(length=128), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_sesion')
    )
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('perfiles_academicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('promedio_general', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estudiante_id')
    )
    op.create_table('desgloses_por_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('promedio_area', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfiles_academicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('numero_preguntas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asignaciones_grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('nombre_grupo', sa.String(length=80), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['docente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuraciones_examen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('numero_alternativas', sa.Integer(), nullable=False),
    sa.Column('puntaje_por_pregunta', sa.Float(), nullable=False),
    sa.Column('penalizacion_por_error', sa.Float(), nullable=False),
    sa.Column('tiempo_limite_minutos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examen_id')
    )
    op.create_table('evoluciones_nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('nota_final', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], ),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfiles_academicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preguntas_banco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('numero_pregunta', sa.Integer(), nullable=False),
    sa.Column('respuesta_correcta', sa.String(length=5), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reportes_institucionales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('generado_en', sa.DateTime(), nullable=True),
    sa.Column('promedio_general', sa.Float(), nullable=False),
    sa.Column('desviacion_estandar', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respuestas_estudiante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('respuestas_marcadas', sa.JSON(), nullable=False),
    sa.Column('ruta_imagen_original', sa.String(length=255), nullable=True),
    sa.Column('procesado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('respuesta_id', sa.Integer(), nullable=False),
    sa.Column('numero_correctas', sa.Integer(), nullable=False),
    sa.Column('numero_incorrectas', sa.Integer(), nullable=False),
    sa.Column('numero_en_blanco', sa.Integer(), nullable=False),
    sa.Column('nota_final', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['respuesta_id'], ['respuestas_estudiante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('respuesta_id')
    )
    op.create_table('estadisticas_grupales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporte_id', sa.Integer(), nullable=False),
    sa.Column('asignacion_grupo_id', sa.Integer(), nullable=False),
    sa.Column('promedio_grupo', sa.Float(), nullable=False),
    sa.Column('numero_aprobados', sa.Integer(), nullable=False),
    sa.Column('numero_desaprobados', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asignacion_grupo_id'], ['asignaciones_grupo.id'], ),
    sa.ForeignKeyConstraint(['reporte_id'], ['reportes_institucionales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estadisticas_grupales')
    op.drop_table('calificaciones')
    op.drop_table('respuestas_estudiante')
    op.drop_table('reportes_institucionales')
    op.drop_table('preguntas_banco')
    op.drop_table('evoluciones_nota')
    op.drop_table('configuraciones_examen')
    op.drop_table('asignaciones_grupo')
    op.drop_table('examenes')
    op.drop_table('desgloses_por_area')
    op.drop_table('perfiles_academicos')
    op.drop_table('materias')
    op.drop_table('credenciales')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))

    op.drop_table('usuarios')
    op.drop_table('areas')
    # ### end Alembic commands ###
